### ISSUE TITLE
[Feat] 검색 뷰 구현

### ISSUE THREAD

**Issue by kpk0616** [Keyneez/Keyneez-iOS#15]
## 🛠 Issue
- 검색 뷰 구현
- Home 뷰 리팩토링

## 📝 To-do

- [x] 세그멘티드컨트롤 해당하는 뷰컨트롤러 하나로 통일시키기
- [x] SwiftLint 오류 해당하는 부분 수정
- [x] 검색 뷰 구현 - Diffable Collectionview
