### ISSUE TITLE
[Feat] 탭바 ID 카드 색상 변경

### ISSUE THREAD

**Issue by kpk0616** [Keyneez/Keyneez-iOS#46]
## 🛠 Issue

유저 정보가 변경되었을 때, 싱글톤에 있는 유저 정보를 받아와 공통 탭바의 ID 카드 컴포넌트의 색상을 변경시킨다.

## 📝 To-do

- [ ] ID 카드 뷰 클래스로 분리
- [ ] ID 카드 뷰에서 가장 상위 계층으로부터 함수 오버라이드, 슬라이딩 효과 구현
- [ ] 싱글톤 유저 정보 변경하는 함수 생성, 유저 정보 request 할 때 실행
- [ ] NotificationCenter 이용해 정보 변경 시 색상 변경
