### ISSUE TITLE
[Feat] 인포 메인 뷰 구현

### ISSUE THREAD

**Issue by kpk0616** [Keyneez/Keyneez-iOS#9]
## 🛠 Issue
인포 메인 뷰 구현

## 📝 To-do

- [x] 상단 검색 바 추가
- [ ] CollectionView diffable 구현
- [ ] 필터 플로팅 버튼
